---

- name: install pm2 process manager globally
  npm: name=pm2 global=yes version=2.0.19 state=present

- name: install pm2 as a service "pm2-init.sh"
  shell: "pm2 startup systemd --user {{ service_user }} --hp ~{{ service_user }}"
  args:
    creates: /etc/systemd/system/pm2.service
