---

- name: Create Ansible configuration file ~/.ansible.cfg
  template: src=.ansible.cfg dest=~/.ansible.cfg

- name: Create Ansible inventory file {{ inventory_path }}
  copy: src=.ansible.ini dest={{ inventory_path }}
