---

- name: Set up /etc/hosts file
  template: src=etc-hosts.txt dest=/etc/hosts mode=644

- name: Test ansible_hostname DNS resolves
  command: ping -c 1 {{ ansible_hostname }}
  tags: test
  changed_when: false

- name: Synchronize apt package index files from their sources
  apt: update_cache=yes

- name: Apt install git
  apt: name=git state=present

- name: mkdir /usr/local/downloads
  file: path=/usr/local/downloads state=directory mode=0755

- name: mkdir /data
  file: path=/data state=directory mode=0755
